source 'https://rubygems.org'

gem 'nokogiri'

gem 'rspec'
gem 'rspec-mocks'
gem 'webmock'
gem 'rack-test'
gem 'coveralls'
gem 'parseconfig'
gem 'pg'
gem 'mimemagic'
gem 'bagit', :git => 'https://github.com/tipr/bagit.git'
gem 'yard'
gem 'rake'
