require_relative 'dspace/item'
require_relative 'dspace/bitstream'
require_relative 'dspace/eperson'
require_relative 'dspace/collection'
require_relative 'dspace/connection'
require_relative 'dspace/metadata_field'
